### ISSUE TITLE
Question about this and firmware settings

### ISSUE THREAD

**Issue by Anarasha** [fieldOfView/Cura-PrinterSettingsPlugin#10]
So, I have a question. Currently I'm gonna use this plugin to make my print time estimates more accurate, but do these settings actually overwrite the firmware defaults like you would by sending terminal commands? 

For instance, if my max speed for X is set to, let's just say 500, in my firmware but I set it to 700 in the printer settings will it become 700 or will Cura just think it's 700? 
Other than that, as usual, thank you for the effort!

**Comment by fieldOfView** [comment]
I would assume that if the firmware value is lower than the gcode value (which is what you set with this plugin) that the firmware version is used. But I would hope that if you set the max speed to a low value in Cura that Cura will not output speeds higher than that. So effectively, with max speeds, the lowest value between what is set in Cura and what is set in the firmware will be used.
