### ISSUE TITLE
Update for Cura 5.0

### ISSUE THREAD

**Issue by bob-anthony** [fieldOfView/Cura-PrinterSettingsPlugin#12]
I've tested this plugin with the latest version of Cura and it works as expected.

Thank you for getting these plugins updated!

**Comment by eben80** [comment]
@bob-anthony How did you install this plugin on Cura 5.0?  I can't seem to find it?

**Comment by bob-anthony** [comment]
@eben80 all this one requires is that the supported sdk versions be updated in plugin.json

**Comment by eben80** [comment]
Could you give me the required changes please? I'd like to try 5.0 but I'm missing firmware retraction setting.

**Comment by bob-anthony** [comment]
I don't know if the developer would appreciate me putting that out. You can however add firmware retraction manually. 

Open the following folder.

%appdata%\cura\5.0\definition_changes

Find the file named like this. 
printer_settings.inst.cfg

Add the following value like so. 
[values]
machine_firmware_retract = True

**Comment by eben80** [comment]
Thank you. That should be sufficient for now.

**Comment by fieldOfView** [comment]
A prerelease version is now available here:
https://github.com/fieldOfView/Cura-PrinterSettingsPlugin/releases/tag/v3.6.0-DEV

For more information about why this update is required, and links to more prereleases, read this post:
https://community.ultimaker.com/topic/40313-fieldofview-plugins-for-cura-50/
