### ISSUE TITLE
Initial Values

### ISSUE THREAD

**Issue by kazooless** [fieldOfView/Cura-PrinterSettingsPlugin#4]
Hello,

Thank you for all your contributions to Cura!

Regarding this plugin, the initial values do not seem to reflect the actual values from the machine definition file. You can see this by installing a Creality3D Ender-3 and then looking at steps per mm for each axis.

I realize there is a "use at your own risk" message in the readme and if these reflected the actual values I believe it would result in safer use of the plugin so someone won't panic when they see these incorrect values.

Thanks again,

kazooless

**Comment by fieldOfView** [comment]
What steps value do you expect? The plugin does not intend to read the value configured in the printer, it intends to show what is configured in Cura. The values you see are the values that are defined in, and used by Cura for your printer. How Cura uses the values, and whether it is a problem that the values don't match what is set in the firmware, is outside of the scope of this plugin. 

For the steps per mm, it would be my guess that a closer match between what is used in Cura and what is specified in the firmware would result in a more accurate print time prediction, but I am not an expert on that.

**Comment by kazooless** [comment]
The correct steps per mm are 80, 80, 400, 93 but the plugin is showing 50, 50, 50, 1600. Are you saying all the values it is showing is indeed reading these values from the printer definition files? If so, then it may be the definition files don't have these specific numbers entered to override the fdmprinter.def file.


<img width="444" alt="Screenshot 2019-12-18 15 47 00" src="https://user-images.githubusercontent.com/9603645/71133034-35de2b00-21ae-11ea-9854-19fbc968dcb3.png">

**Comment by fieldOfView** [comment]
The values you say are not anywhere in the printer definition for the Ender 3. As a matter of fact, no Creality printer defines any Steps per Millimeter value in the printer definitions in Cura, so they default to the value specified in fdmprinter.def.json.

In other words: the plugin is working as expected here.
