### ISSUE TITLE
Cura V4.6.1 + Cura-PrinterSettingsPlugin V3.5.3 - printer menue does not show up and unreasonable defaults

### ISSUE THREAD

**Issue by elsbiet** [fieldOfView/Cura-PrinterSettingsPlugin#6]
the printer menue does not show up - neither in siedebar nor in  preferences->configure cura->printer->printer settings

moreover default numerical values e.g. for maximum speed [xyz] and feedrate are unreasonable high (2997924580 - uninitialized variable?)

**Comment by fieldOfView** [comment]
Please clarify. What printer menu are you talking about? If you mean the "Printer Settings" catagory, I can't help but wonder how you can see the "unreasonable defaults" for some settings in that catagory.

As for the defaults, those values are set by the printer definition, not by this plugin. 2997924580 mm/s is the speed of light, and basically means there is no maximum speed set; "as fast as physically possible".

**Comment by elsbiet** [comment]
1. i mean, i cannot see any subnodes (or leafs) in the sidebar (i'm not very familiar with modern user interface vocabulary)

2. where can i find the default values in the printer definition?

**Comment by fieldOfView** [comment]
1. Could you add a screenshot of how you found the maximum speed and feedrate settings then?

2. That depends on the type of printer you use. Did you add a Custom FFF Printer, or a predefined printer from the Add Printer list?

**Comment by elsbiet** [comment]
1. i found the maximum speed and feedrate by entering maxi into the print settings search field

2. i added a custom fff printer, a self build one (blv mgn)

**Comment by fieldOfView** [comment]
Could you post a link to your Cura.log? See help->show configuration folder. Please upload the file to eg google dive or dropbox and share a link here.

Cura does not know what the maximum print speed of your self-built printer is, so it tries not to limit speeds leaving the maximum speed up to the firmware of your printer. This part is not a bug, it is how Cura works,

**Comment by elsbiet** [comment]
i'll post the cura later (after finishing my bread & butter job). is there anything special i should do within  cura after i've started it and before i send the .log file?

is there a way to make cura aware of my self-build printer?

**Comment by elsbiet** [comment]
here is the requested cura-log and 2 screendumps:

0. the preferences window - the node is not expandable
1. print settings - no printer settings node visible
2. print settings after searching for maxi
![printer - printer-settings-0](https://user-images.githubusercontent.com/15084356/81266114-7d256500-9044-11ea-93ea-5753d9fd44b8.jpg)
![printer - printer-settings-1](https://user-images.githubusercontent.com/15084356/81266124-81518280-9044-11ea-83a4-e57b1a3374d0.jpg)
![printer - printer-settings-2](https://user-images.githubusercontent.com/15084356/81266135-87476380-9044-11ea-9dc0-b18320b56c5f.jpg)


[cura-printer-settings.log](https://github.com/fieldOfView/Cura-PrinterSettingsPlugin/files/4591290/cura-printer-settings.log)

![Screenshot from 2020-05-07 09-07-38](https://user-images.githubusercontent.com/15084356/81264933-87466400-9042-11ea-8402-bcc48bf404a8.png)

**Comment by fieldOfView** [comment]
Thanks for the logs. As I somewhat expected, they don't show anything out of the ordinary.

In Cura, categories that don't have any settings shown are hidden. In your screenshots, I don't see any settings that are "shown". If you right click on eg the Maximum Feedrate setting, and select "Keep this setting visible", the setting should remain in the sidebar (in the Printer Settings category) when you clear the search box. This is how all the other categories behave too.

**Comment by fieldOfView** [comment]
If you have selected "All" in the setting visibility profile dropdown before, you may have to select that again; the "All" option is really only all the settings that are currently available. The plugin adds new settings, and those are not included by the previous "All".

**Comment by elsbiet** [comment]
thanks, that did the trick.

for the sake of completeness it would be nice to know how to make cura aware of my self build printer.

**Comment by fieldOfView** [comment]
You would have to create a "definition" for your printer (such as those in the /resources/definitions and /resources/extruders folders) and include maximum speeds etc in those definitions. But that is outside the realm of this plugin, so I refer you to the Ultimaker/Cura issue queue for that.

The defaults don't hurt your printer; the firmware will limit the maximum speeds. The only problem with leaving the defaults as is is that Cura will be less accurate when predicting print times (because it won't know what exact speed the printer will be moving at).
