### ISSUE TITLE
Filament Park Distance was removed in 4.6

### ISSUE THREAD

**Issue by konskarm** [fieldOfView/Cura-PrinterSettingsPlugin#7]
The setting "Filament Park Distance" was removed from fdmprinter in 4.6, as it can be seen in https://github.com/Ultimaker/Cura/commit/b5dfcdd48283c974e08e3756b0cfc835869fd7b8.

**Comment by fieldOfView** [comment]
The plugin only mirrors settings from the "machine_settings" category to a newly created "printer_settings" category. It has a blacklist for some printers, but it does not introduce settings that are not already available in the fdmprinter.def.json file.

Are you running Cura 4.6 from source or from a frozen release?

**Comment by konskarm** [comment]
Ah, my bad. I was indeed in an old branch while I was checking it. I do not see it in master.
