### ISSUE TITLE
Machine settings not visible in Cura 4.8

### ISSUE THREAD

**Issue by 5axes** [fieldOfView/Cura-PrinterSettingsPlugin#9]
Tested With and Without the Sidebarplugin and in both case we don't have the section related to the machine settings.

In the log file nothing special as message regarding this plugin ....
![MachineSettings](https://user-images.githubusercontent.com/11015345/97163401-e0d15500-1780-11eb-930e-c0785093a331.JPG)
[cura-log.zip](https://github.com/fieldOfView/Cura-PrinterSettingsPlugin/files/5438311/cura-log.zip)

`- INFO - [MainThread] UM.Logger.info [122]: Loaded plugin PrinterSettingsPlugin`

**Comment by fieldOfView** [comment]
I can't reproduce this. 
Try the search to look for the "Nozzle diameter" setting for example.

**Comment by fieldOfView** [comment]
If no setting in the Printer Settings category is made visible, the category will be hidden.

**Comment by 5axes** [comment]
Ok I think it was an issue with the Sidebar gui , with the last release it's now ok in the beta 4.8

**Comment by evilC** [comment]
> If no setting in the Printer Settings category is made visible, the category will be hidden.

It may be worth adding this fact to the description or something? Not many people are familiar with how to search GitHub for closed issues, and that's the only way I worked out why I was seeing no difference with this plugin installed
